# Generated by Django 6.1.1 on 2026-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
