# Generated by Django 6.1.1 on 2026-09-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0006_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
