# Generated by Django 6.1.1 on 2026-09-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='storereview',
            name='user',
        ),
        migrations.AddField(
            model_name='storereview',
            name='review_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storereview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storereview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chai.store'),
        ),
    ]
